// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNode_DataNodeServerMonitor.proto

package com.hyz.proto;

public final class NameNode_DataNodeServerMonitor {
  private NameNode_DataNodeServerMonitor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code meta.DataNodeLeaderState}
   */
  public enum DataNodeLeaderState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * DataNode 集群正在通过 MyRaft 协议选举出新的 Leader，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>RaftVote = 0;</code>
     */
    RaftVote(0),
    /**
     * <pre>
     * DataNode 集群超过半数宕机，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>RaftCrash = 1;</code>
     */
    RaftCrash(1),
    /**
     * <pre>
     * DataNode 集群正在恢复备份，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>LeaderRecovery = 2;</code>
     */
    LeaderRecovery(2),
    /**
     * <pre>
     * DataNode Leader 正常运行
     * </pre>
     *
     * <code>LeaderOK = 3;</code>
     */
    LeaderOK(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * DataNode 集群正在通过 MyRaft 协议选举出新的 Leader，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>RaftVote = 0;</code>
     */
    public static final int RaftVote_VALUE = 0;
    /**
     * <pre>
     * DataNode 集群超过半数宕机，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>RaftCrash = 1;</code>
     */
    public static final int RaftCrash_VALUE = 1;
    /**
     * <pre>
     * DataNode 集群正在恢复备份，此时不会返回任何 rpc 地址
     * </pre>
     *
     * <code>LeaderRecovery = 2;</code>
     */
    public static final int LeaderRecovery_VALUE = 2;
    /**
     * <pre>
     * DataNode Leader 正常运行
     * </pre>
     *
     * <code>LeaderOK = 3;</code>
     */
    public static final int LeaderOK_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataNodeLeaderState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataNodeLeaderState forNumber(int value) {
      switch (value) {
        case 0: return RaftVote;
        case 1: return RaftCrash;
        case 2: return LeaderRecovery;
        case 3: return LeaderOK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataNodeLeaderState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataNodeLeaderState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataNodeLeaderState>() {
            public DataNodeLeaderState findValueByNumber(int number) {
              return DataNodeLeaderState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hyz.proto.NameNode_DataNodeServerMonitor.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataNodeLeaderState[] VALUES = values();

    public static DataNodeLeaderState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataNodeLeaderState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:meta.DataNodeLeaderState)
  }

  public interface GetDataNodeLeaderRPCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meta.GetDataNodeLeaderRPCResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * DataNode 状态
     * </pre>
     *
     * <code>.meta.DataNodeLeaderState State = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <pre>
     * DataNode 状态
     * </pre>
     *
     * <code>.meta.DataNodeLeaderState State = 1;</code>
     * @return The state.
     */
    com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState getState();

    /**
     * <pre>
     * LeaderOK 状态下，返回 ip + 端口
     * </pre>
     *
     * <code>string LeaderRPCUri = 2;</code>
     * @return The leaderRPCUri.
     */
    java.lang.String getLeaderRPCUri();
    /**
     * <pre>
     * LeaderOK 状态下，返回 ip + 端口
     * </pre>
     *
     * <code>string LeaderRPCUri = 2;</code>
     * @return The bytes for leaderRPCUri.
     */
    com.google.protobuf.ByteString
        getLeaderRPCUriBytes();
  }
  /**
   * <pre>
   * 场景一：NameNode 获取 DataNode Leader 的 rpc 服务地址
   * 不需要 Request 信息
   * </pre>
   *
   * Protobuf type {@code meta.GetDataNodeLeaderRPCResponse}
   */
  public static final class GetDataNodeLeaderRPCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meta.GetDataNodeLeaderRPCResponse)
      GetDataNodeLeaderRPCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetDataNodeLeaderRPCResponse.newBuilder() to construct.
    private GetDataNodeLeaderRPCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDataNodeLeaderRPCResponse() {
      state_ = 0;
      leaderRPCUri_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetDataNodeLeaderRPCResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetDataNodeLeaderRPCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderRPCUri_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hyz.proto.NameNode_DataNodeServerMonitor.internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hyz.proto.NameNode_DataNodeServerMonitor.internal_static_meta_GetDataNodeLeaderRPCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.class, com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <pre>
     * DataNode 状态
     * </pre>
     *
     * <code>.meta.DataNodeLeaderState State = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * DataNode 状态
     * </pre>
     *
     * <code>.meta.DataNodeLeaderState State = 1;</code>
     * @return The state.
     */
    @java.lang.Override public com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState getState() {
      @SuppressWarnings("deprecation")
      com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState result = com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.valueOf(state_);
      return result == null ? com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.UNRECOGNIZED : result;
    }

    public static final int LEADERRPCURI_FIELD_NUMBER = 2;
    private volatile java.lang.Object leaderRPCUri_;
    /**
     * <pre>
     * LeaderOK 状态下，返回 ip + 端口
     * </pre>
     *
     * <code>string LeaderRPCUri = 2;</code>
     * @return The leaderRPCUri.
     */
    @java.lang.Override
    public java.lang.String getLeaderRPCUri() {
      java.lang.Object ref = leaderRPCUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderRPCUri_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * LeaderOK 状态下，返回 ip + 端口
     * </pre>
     *
     * <code>string LeaderRPCUri = 2;</code>
     * @return The bytes for leaderRPCUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderRPCUriBytes() {
      java.lang.Object ref = leaderRPCUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderRPCUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.RaftVote.getNumber()) {
        output.writeEnum(1, state_);
      }
      if (!getLeaderRPCUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderRPCUri_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.RaftVote.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (!getLeaderRPCUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderRPCUri_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse)) {
        return super.equals(obj);
      }
      com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse other = (com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse) obj;

      if (state_ != other.state_) return false;
      if (!getLeaderRPCUri()
          .equals(other.getLeaderRPCUri())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + LEADERRPCURI_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderRPCUri().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 场景一：NameNode 获取 DataNode Leader 的 rpc 服务地址
     * 不需要 Request 信息
     * </pre>
     *
     * Protobuf type {@code meta.GetDataNodeLeaderRPCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meta.GetDataNodeLeaderRPCResponse)
        com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hyz.proto.NameNode_DataNodeServerMonitor.internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hyz.proto.NameNode_DataNodeServerMonitor.internal_static_meta_GetDataNodeLeaderRPCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.class, com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.Builder.class);
      }

      // Construct using com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = 0;

        leaderRPCUri_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hyz.proto.NameNode_DataNodeServerMonitor.internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor;
      }

      @java.lang.Override
      public com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse getDefaultInstanceForType() {
        return com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse build() {
        com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse buildPartial() {
        com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse result = new com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse(this);
        result.state_ = state_;
        result.leaderRPCUri_ = leaderRPCUri_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse) {
          return mergeFrom((com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse other) {
        if (other == com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (!other.getLeaderRPCUri().isEmpty()) {
          leaderRPCUri_ = other.leaderRPCUri_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       * DataNode 状态
       * </pre>
       *
       * <code>.meta.DataNodeLeaderState State = 1;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       * DataNode 状态
       * </pre>
       *
       * <code>.meta.DataNodeLeaderState State = 1;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DataNode 状态
       * </pre>
       *
       * <code>.meta.DataNodeLeaderState State = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState getState() {
        @SuppressWarnings("deprecation")
        com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState result = com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.valueOf(state_);
        return result == null ? com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * DataNode 状态
       * </pre>
       *
       * <code>.meta.DataNodeLeaderState State = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.hyz.proto.NameNode_DataNodeServerMonitor.DataNodeLeaderState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DataNode 状态
       * </pre>
       *
       * <code>.meta.DataNodeLeaderState State = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leaderRPCUri_ = "";
      /**
       * <pre>
       * LeaderOK 状态下，返回 ip + 端口
       * </pre>
       *
       * <code>string LeaderRPCUri = 2;</code>
       * @return The leaderRPCUri.
       */
      public java.lang.String getLeaderRPCUri() {
        java.lang.Object ref = leaderRPCUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderRPCUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * LeaderOK 状态下，返回 ip + 端口
       * </pre>
       *
       * <code>string LeaderRPCUri = 2;</code>
       * @return The bytes for leaderRPCUri.
       */
      public com.google.protobuf.ByteString
          getLeaderRPCUriBytes() {
        java.lang.Object ref = leaderRPCUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderRPCUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * LeaderOK 状态下，返回 ip + 端口
       * </pre>
       *
       * <code>string LeaderRPCUri = 2;</code>
       * @param value The leaderRPCUri to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderRPCUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderRPCUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LeaderOK 状态下，返回 ip + 端口
       * </pre>
       *
       * <code>string LeaderRPCUri = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderRPCUri() {
        
        leaderRPCUri_ = getDefaultInstance().getLeaderRPCUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LeaderOK 状态下，返回 ip + 端口
       * </pre>
       *
       * <code>string LeaderRPCUri = 2;</code>
       * @param value The bytes for leaderRPCUri to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderRPCUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderRPCUri_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meta.GetDataNodeLeaderRPCResponse)
    }

    // @@protoc_insertion_point(class_scope:meta.GetDataNodeLeaderRPCResponse)
    private static final com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse();
    }

    public static com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDataNodeLeaderRPCResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetDataNodeLeaderRPCResponse>() {
      @java.lang.Override
      public GetDataNodeLeaderRPCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetDataNodeLeaderRPCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDataNodeLeaderRPCResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetDataNodeLeaderRPCResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hyz.proto.NameNode_DataNodeServerMonitor.GetDataNodeLeaderRPCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meta_GetDataNodeLeaderRPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$NameNode_DataNodeServerMonitor.proto\022\004" +
      "meta\032\033google/protobuf/empty.proto\"^\n\034Get" +
      "DataNodeLeaderRPCResponse\022(\n\005State\030\001 \001(\016" +
      "2\031.meta.DataNodeLeaderState\022\024\n\014LeaderRPC" +
      "Uri\030\002 \001(\t*T\n\023DataNodeLeaderState\022\014\n\010Raft" +
      "Vote\020\000\022\r\n\tRaftCrash\020\001\022\022\n\016LeaderRecovery\020" +
      "\002\022\014\n\010LeaderOK\020\0032f\n\026DataNodeMonitorServic" +
      "e\022L\n\014GetLeaderRPC\022\026.google.protobuf.Empt" +
      "y\032\".meta.GetDataNodeLeaderRPCResponse0\001B" +
      "1\n\rcom.hyz.protoB\036NameNode_DataNodeServe" +
      "rMonitorP\000P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meta_GetDataNodeLeaderRPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meta_GetDataNodeLeaderRPCResponse_descriptor,
        new java.lang.String[] { "State", "LeaderRPCUri", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
